@testable import Bottles
import Testing
import Foundation
import CoreGraphics

struct PreparerTests {
    @Test("nextStage gives Singer with same specifications")
    func nextStage() throws {
        let subject = Preparer(bottleNumber: 99, interactive: false)
        let nextState = try #require(subject.nextState() as? Singer)
        #expect(nextState.bottleNumber == 99)
        #expect(nextState.interactive == false)
        #expect(nextState.verse == subject.verse)
    }

    @Test("99 gives correct verse")
    func verse99() {
        let bottleLayer = MockBottleLayer(bottleNumber: 5, scale: 2, screenBounds: .zero)
        let subject = Preparer(bottleNumber: 99, interactive: false)
        let verse = subject.verse
        #expect(verse.count == 10)
        #expect(verse[0].sound == "ninety1")
        #expect(verse[1].sound == "nine1")
        #expect(verse[2].sound == "bottles1")
        #expect(verse[3].sound == "ninety2")
        #expect(verse[4].sound == "nine2")
        #expect(verse[5].sound == "bottles2")
        #expect(verse[6].sound == "take")
        #expect(verse[7].sound == "ninety3")
        #expect(verse[8].sound == "eight3")
        #expect(verse[9].sound == "bottles3")
        #expect(verse[0].pauseAfterwards == false)
        #expect(verse[1].pauseAfterwards == false)
        #expect(verse[2].pauseAfterwards == false)
        #expect(verse[3].pauseAfterwards == false)
        #expect(verse[4].pauseAfterwards == false)
        #expect(verse[5].pauseAfterwards == false)
        #expect(verse[6].pauseAfterwards == false)
        #expect(verse[7].pauseAfterwards == false)
        #expect(verse[8].pauseAfterwards == false)
        #expect(verse[9].pauseAfterwards == false)
        #expect(verse[0].action == nil)
        #expect(verse[1].action == nil)
        #expect(verse[2].action == nil)
        #expect(verse[3].action == nil)
        #expect(verse[4].action == nil)
        #expect(verse[5].action == nil)
        #expect(verse[6].action != nil)
        verse[6].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()"])
        #expect(verse[7].action == nil)
        #expect(verse[8].action == nil)
        #expect(verse[9].action != nil)
        verse[9].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()", "flyAway()"])
    }

    @Test("99 gives correct verse if interactive")
    func verse99interactive() {
        let bottleLayer = MockBottleLayer(bottleNumber: 5, scale: 2, screenBounds: .zero)
        let subject = Preparer(bottleNumber: 99, interactive: true) // *
        let verse = subject.verse
        #expect(verse.count == 10)
        #expect(verse[0].sound == "ninety1")
        #expect(verse[1].sound == "nine1")
        #expect(verse[2].sound == "bottles1")
        #expect(verse[3].sound == "ninety2")
        #expect(verse[4].sound == "nine2")
        #expect(verse[5].sound == "bottles2")
        #expect(verse[6].sound == "take")
        #expect(verse[7].sound == "ninety3")
        #expect(verse[8].sound == "eight3")
        #expect(verse[9].sound == "bottles3")
        #expect(verse[0].pauseAfterwards == false)
        #expect(verse[1].pauseAfterwards == false)
        #expect(verse[2].pauseAfterwards == false)
        #expect(verse[3].pauseAfterwards == false)
        #expect(verse[4].pauseAfterwards == false)
        #expect(verse[5].pauseAfterwards == true) // *
        #expect(verse[6].pauseAfterwards == false)
        #expect(verse[7].pauseAfterwards == false)
        #expect(verse[8].pauseAfterwards == false)
        #expect(verse[9].pauseAfterwards == false)
        #expect(verse[0].action == nil)
        #expect(verse[1].action == nil)
        #expect(verse[2].action == nil)
        #expect(verse[3].action == nil)
        #expect(verse[4].action == nil)
        #expect(verse[5].action == nil)
        #expect(verse[6].action != nil)
        verse[6].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()"])
        #expect(verse[7].action == nil)
        #expect(verse[8].action == nil)
        #expect(verse[9].action != nil)
        verse[9].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()", "flyAway()"])
    }

    @Test("2 gives correct verse")
    func verse2() {
        let bottleLayer = MockBottleLayer(bottleNumber: 5, scale: 2, screenBounds: .zero)
        let subject = Preparer(bottleNumber: 2, interactive: false)
        let verse = subject.verse
        #expect(verse.count == 6)
        #expect(verse[0].sound == "two1")
        #expect(verse[1].sound == "bottles1")
        #expect(verse[2].sound == "two2")
        #expect(verse[3].sound == "bottles2")
        #expect(verse[4].sound == "take")
        #expect(verse[5].sound == "onefinal1")
        #expect(verse[0].pauseAfterwards == false)
        #expect(verse[1].pauseAfterwards == false)
        #expect(verse[2].pauseAfterwards == false)
        #expect(verse[3].pauseAfterwards == false)
        #expect(verse[4].pauseAfterwards == false)
        #expect(verse[5].pauseAfterwards == false)
        #expect(verse[0].action == nil)
        #expect(verse[1].action == nil)
        #expect(verse[2].action == nil)
        #expect(verse[3].action == nil)
        #expect(verse[4].action != nil)
        verse[4].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()"])
        #expect(verse[5].action != nil)
        verse[5].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()", "flyAway()"])
    }

    @Test("2 gives correct verse interactive")
    func verse2interactive() {
        let bottleLayer = MockBottleLayer(bottleNumber: 5, scale: 2, screenBounds: .zero)
        let subject = Preparer(bottleNumber: 2, interactive: true)
        let verse = subject.verse
        #expect(verse.count == 6)
        #expect(verse[0].sound == "two1")
        #expect(verse[1].sound == "bottles1")
        #expect(verse[2].sound == "two2")
        #expect(verse[3].sound == "bottles2")
        #expect(verse[4].sound == "take")
        #expect(verse[5].sound == "onefinal1")
        #expect(verse[0].pauseAfterwards == false)
        #expect(verse[1].pauseAfterwards == false)
        #expect(verse[2].pauseAfterwards == false)
        #expect(verse[3].pauseAfterwards == true)
        #expect(verse[4].pauseAfterwards == false)
        #expect(verse[5].pauseAfterwards == false)
        #expect(verse[0].action == nil)
        #expect(verse[1].action == nil)
        #expect(verse[2].action == nil)
        #expect(verse[3].action == nil)
        #expect(verse[4].action != nil)
        verse[4].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()"])
        #expect(verse[5].action != nil)
        verse[5].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()", "flyAway()"])
    }

    @Test("1 gives correct verse")
    func verse1() {
        let bottleLayer = MockBottleLayer(bottleNumber: 5, scale: 2, screenBounds: .zero)
        let subject = Preparer(bottleNumber: 1, interactive: false)
        let verse = subject.verse
        #expect(verse.count == 3)
        #expect(verse[0].sound == "onefinal2")
        #expect(verse[1].sound == "onefinal3")
        #expect(verse[2].sound == "onefinal4")
        #expect(verse[0].pauseAfterwards == false)
        #expect(verse[1].pauseAfterwards == false)
        #expect(verse[2].pauseAfterwards == false)
        #expect(verse[0].action == nil)
        #expect(verse[1].action != nil)
        verse[1].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()"])
        #expect(verse[2].action != nil)
        verse[2].action?(bottleLayer)
        #expect(bottleLayer.methodsCalled == ["jiggle()", "flyAway()"])
    }

    @Test("1 gives correct verse interactive")
    func verse1interactive() {
        let subject = Preparer(bottleNumber: 1, interactive: true)
        let verse = subject.verse
        #expect(verse.count == 3)
        #expect(verse[0].sound == "onefinal2")
        #expect(verse[1].sound == "onefinal3")
        #expect(verse[2].sound == "onefinal4")
        #expect(verse[0].pauseAfterwards == false)
        #expect(verse[1].pauseAfterwards == false)
        #expect(verse[2].pauseAfterwards == false)
        #expect(verse[0].action == nil)
        #expect(verse[1].action != nil)
        #expect(verse[2].action != nil)
    }
}
